### ISSUE TITLE
Optionally use convex hull of mesh shapes

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/sdformat#68]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/68)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
There are computational advantages to collision detection using convex meshes. It would be useful for users who carefully construct their own convex meshes to be able to declare that they are convex. Then the collision engine can make smarter choices.

@erwincoumans @hsu 

See also [issue about gazebo-bullet concave mesh support](https://github.com/gazebosim/gazebo-classic/issues/514) for commentary on the challenges of real-time decomposition of concave meshes to convex. Using a flag will be computationally faster.

**Comment by iche033** [comment]
I like the idea of using a flag to explicitly indicate that we want to decompose / or simplify the mesh.

One idea is to use a new attribute, `simplify` (open to suggestion), in `<mesh>`:

```xml
<collision name="my_collision">
  <geometry>
    <mesh simplify="convex">
      <uri>path_to_complex_mesh</uri>
    </mesh>
  </geometry>
</collision>
```

Ways to simplify a mesh:
* `convex` - decomposes the mesh to one or multiple simple convex meshes. This can be done by the physics engine's if available (e.g. bullet's `btConvexHullShape`) or use other libraries for decomposition, e.g. https://github.com/kmammou/v-hacd
* `bounding_box` - Most simple option - just use the object's bounding box as the collision. 
* `simple_shapes` - decomposes to a set of simple shapes (instead of simple convex meshes)

**Comment by scpeters** [comment]
a `//mesh/@optimization` attribute has been added in https://github.com/gazebosim/sdformat/pull/1382
